# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', '/vendor/']


# Site Settings
title: "Stadia Conference 2025"
email: "stadiawc2025@stadia.com"
description: "Stadia Web Conferece 2025"
baseurl: "/2025"
url: "https://stadiawc2025.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "stadiawc2025.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Future Reference Syndicate"
organizerAlternateName: "Group Future Reference Syndicate"
organizerDescription: "Non-profit organisation that brings together visionaries in the field of media and communication."
organizerEmail: "frs@stadia.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@stadia2025"
socialImageSrcGooglePlus: "/img/seo/stadia-logo.svg"
socialImageSrcTwitter: "/img/seo/stadia-logo.svg"
socialImageSrcFacebook: "/img/seo/stadia-logo.svg"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/program/", text: "Program"}
 - {permalink: "/speakers/", text: "Keynote Speakers"}
 - {permalink: "/facilities/", text: "Facilities"}
 - {permalink: "/sponsors/", text: "Sponsors"}
 - {permalink: "/register/", text: "Register"}
 - {permalink: "/contact/", text: "Contact"}
 - {permalink: "/about/", text: "About us"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Stadia Web Conference 2025"
eventDate: "September 1st, 2025"

# About Block
aboutTitle: "About Stadia Web Conference 2025"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Videogames related event in the this year carefully crafted for you by FRS community! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops. Come and tame your favourite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building ? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "5000", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "8", specialCharacter: "+", info: "hours", detail: "of the most brand new announcements of the world of videogames!"}
 - {count: "5", specialCharacter: "+", info: "speakers", detail: "worldwide known"}

# Latest News Block
latestNewsTitle: "Latest news"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "stadiawc2025"

# Partners Block
organizersTitle: "Organizers"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Sign up to attend to the biggest online event this year!"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around mid of August. Number of tickets are limited. Stay tuned!"

# Footer
footerBlocks:
 -
  title: "Chamber of Commerce Number"
  links:
   - {text: "1.61.80.34.05"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "We are a non-profit organisation that brings together visionaries in the field of media and communication. We started out in November of 2017 and have since then grown to an organisation of 3 staff-members and numerous volunteers.
These permanent staff-members are:"

# Contact Block
contactTitle: "How to get in touch with us?"
contactBlock:
 - {title: "Email", image: "email.jpg", text: "Here you have the email of the organization: frs@stadia.com" }
 - {title: "RSS", image: "twitter.jpg", text: "We only have an official account on Twitter: @stadiawc2025" }

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Hackathon: Meet our themes"
hackathonRows:
 - {title: "VR experience on FIFA 25", details: "Challenge: Experience how would be to play as professional football player through a VR implementation! The winner will have a chance to implement it for the next edition of FIFA"}
 - {title: "Develop a 2D videogame in less than 2 hours", details: "Find the quickest way to develop a simple but addictive videogame. This session will be hosted by Hideo Kojima"}

